### ISSUE TITLE
"the proof" is not working

### ISSUE THREAD

**Issue by carlodri** [ikalnytskyi/sphinxcontrib-redoc#17]
[the proof](https://sphinxcontrib-redoc.readthedocs.io/en/latest/api/github/) for me just shows an endless "Loading"...

**Comment by ikalnytskyi** [comment]
@carlodri thanks for reporting! fixed in https://github.com/ikalnytskyi/sphinxcontrib-redoc/commit/3b881bd1b3119b6375a1b64d9eed03f446c7bdc5
