### ISSUE TITLE
openapi: 3.0.1 support

### ISSUE THREAD

**Issue by marfillaster** [ikalnytskyi/sphinxcontrib-redoc#18]
since `redoc@2.0.0-alpha.x` there is support for `opeapi: 3.0.1`

**Comment by marfillaster** [comment]
In conf.py
```
redoc_uri = 'https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js'
```

**Comment by ikalnytskyi** [comment]
@marfillaster em.. what? :) Is it just a "FYI" or a bug report that it does not work?

**Comment by marfillaster** [comment]
Lol. More like FYI after 5 minutes I posted the issue.
