### ISSUE TITLE
Move to sphinx-contrib organization?

### ISSUE THREAD

**Issue by stephenfin** [ikalnytskyi/sphinxcontrib-redoc#21]
As with https://github.com/sphinx-contrib/openapi/issues/23, this could be beneficial to the long term visibility/sustainability of the project. Let me know if you agree/disagree or have any questions!

**Comment by stephenfin** [comment]
Any updates on this, @ikalnytskyi ?

**Comment by ikalnytskyi** [comment]
@stephenfin Sorry, I've been busy recently. Can we move it now?

**Comment by stephenfin** [comment]
Go for it. Process should be the same as https://github.com/sphinx-contrib/openapi/issues/23#issuecomment-443400396 (and remember to drop the `sphinxcontrib-` bit) If there are permissions issues, I'll rectify them straight away. Let me know if you've any questions :smile:

**Comment by ikalnytskyi** [comment]
@stephenfin I moved and apparently lost admin permissions (I cannot even open a Settings page). Can you please help me?

**Comment by stephenfin** [comment]
Yup, fixed now. You should have admin rights once again.

**Comment by ikalnytskyi** [comment]
Cool, thanks!
