### ISSUE TITLE
TypeError('sequence item 0: expected str instance, int found',) when we do make html

### ISSUE THREAD

**Issue by kadogo** [ikalnytskyi/sphinxcontrib-redoc#28]
Hello I have the following error when I do "make html" in my doc directory

```
TypeError('sequence item 0: expected str instance, int found',)
```

If I do the following change in my conf.py it remove the error, it is normal ?

```
            'expand-responses': [ 200, 201 ],
```

```
            'expand-responses': [ "200", "201" ],
```

Cheers.

**Comment by ikalnytskyi** [comment]
Hey @kadogo, thanks for the feedback! Apparently it was a bug in the docs. It was fixed in c12e231dae18afd02b7b75c506e71d5be8363cfb. Moreover, the code in master now throws a human readable error if these values aren't strings. I plan to release a new version really soon. Sorry for inconvenience.
