### ISSUE TITLE
The generated doc don't show any exemple of request and response

### ISSUE THREAD

**Issue by kadogo** [ikalnytskyi/sphinxcontrib-redoc#30]
Hello

I see that I have examples in my openapi.yaml (https://gitlab.fusiondirectory.org/fusiondirectory/fd-plugins/raw/1.4-dev/webservice/html/openapi.yaml) but nothing is shown in the generated documentation.

I also set in my conf.py the following opts

```
'expand-responses': [ "200", "201" ],
```

Cheers.

**Comment by kadogo** [comment]
At end it work now that I use the latest standalone version of redoc 

```
redoc_uri = 'https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js'
```

**Comment by ikalnytskyi** [comment]
Looks like you use OpenAPI v3, and latest stable ReDoc is only OpenAPI v2 compatible. The latest unstable version (i.e. `redoc@next`) works with OpenAPI v3. I'll the this plugin once ReDoc v2 that supports OpenAPI v3 is released.
