### ISSUE TITLE
Minor Issue in docs

### ISSUE THREAD

**Issue by CITIZENDOT** [ikalnytskyi/sphinxcontrib-redoc#35]
#### Here's the screenshot of the [docs](https://sphinxcontrib-redoc.readthedocs.io/en/stable/)
![SphinxRedoc](https://user-images.githubusercontent.com/52322531/111580724-ed962a00-87af-11eb-8400-e1a7a203a132.png)
There is **no semicolon** here. But In the [source](https://github.com/sphinx-contrib/redoc/blob/master/docs/index.rst) It is present. I wonder how it's missing here.

**Comment by ikalnytskyi** [comment]
It seems the docs are rendered from `v1.5.1` tag, while `v1.6.0` is the last and includes the fix (https://github.com/sphinx-contrib/redoc/commit/fb4fee642a4336361a8bcac814cb574f7cc48e34).

**Comment by ikalnytskyi** [comment]
Just rebuilt the docs. Thank you for noticing that. 

![image](https://user-images.githubusercontent.com/166626/114707257-acebeb00-9d32-11eb-867f-5f1b6cdfa427.png)
