### ISSUE TITLE
Redoc 2

### ISSUE THREAD

**Issue by Kobzol** [ikalnytskyi/sphinxcontrib-redoc#9]
Redoc just released version 2 alpha with support for OpenAPI 3, is there any plan to support the newest Redoc? :-)

**Comment by ikalnytskyi** [comment]
Sure thing! :) I'll work on this over weekend. Thanks for reporting, I didn't follow redoc releases for quite a time.

**Comment by ikalnytskyi** [comment]
Well, I [deployed alpha version to PyPI](https://pypi.org/project/sphinxcontrib-redoc/2.0.0a1/) (`sphinxcontrib-redoc == 2.0.0a1`) so please feel free to give it a try. :) I decided to call it *alpha*, because ReDoc 2 is still in alpha.

**Comment by Kobzol** [comment]
Awesome! You're fast as lightning :-) It works for my version 3 spec. Now if only it worked for local files, but that's a separate issue :-) Thank you.

**Comment by ikalnytskyi** [comment]
> Now if only it worked for local files, but that's a separate issue

What do you mean? I checked it with local v2 spec, everything seems working fine. No?

**Comment by Kobzol** [comment]
Redoc cannot load local files (protocol file:///), I have to serve the spec on a web server. I thought it's a known issue (https://github.com/Rebilly/ReDoc/issues/149).

**Comment by pohutukawa** [comment]
Actually, what #18 suggests has worked quite well for me. I'm not aware of any problems, yet, but just adding the following line in my `conf.py` has worked like a charm:

```python
redoc_uri = 'https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js'
```

Now it's rendering using the latest RC of ReDoc 2.0, even though I'm still using version 1.5.1 of  the redoc extension ...
